# Yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 'Lint PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read
  statuses: write # https://github.com/amannn/action-semantic-pull-request/issues/249#issuecomment-2019942359

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          wip: true
